apiVersion: v1
entries:
  easyhaproxy:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2024-01-12T20:37:13.96435615Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 02c7ad34d1e5e87c34b7bc92791585f5223dad804b367eec423649008430f90b
    icon: https://opensource.byjg.com/devops/docker-easy-haproxy/logo.png
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 4.3.1-rc1
    created: "2024-01-12T20:37:13.964006183Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 585ff193a79065e2a8680bb10dda2631c92a22e2f3c8332f8e319453dfaae8d2
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 4.3.0
    created: "2024-01-12T20:37:13.96351417Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 3d36cdb187b11bb71667286593f0f58da93312c59fbc27ff166b7d8e7921412c
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 4.2.0
    created: "2024-01-12T20:37:13.963196103Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: 2f2ef5dba014e2e308ea7b1d7034a43b214839449dddcbedc04933d8fe1f77a4
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: master
    created: "2024-01-12T20:37:13.962880702Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a111f02e52ff8b1c8be11f32c5a5ed43ad7f3cb6108d74de296a774e3dbc28a0
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: test
    created: "2024-01-12T20:37:13.962559499Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a5dee1fe1c339cb4916fc076657db77957d12a2c87279acab1fded1501196e87
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: test
    created: "2024-01-12T20:37:13.962077514Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: e2019a2ec047d4289cabe25b7556b74411689e1612505a787ddd6c6d7730ce53
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: test
    created: "2024-01-12T20:37:13.961617681Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: fcdf99bf482fd2830f1a6de441aa8d5d7dfc973633a035c063ad9a1bf9bb9f93
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.0.tgz
    version: 0.1.0
  static-httpserver:
  - apiVersion: v2
    appVersion: latest
    created: "2024-01-12T20:37:13.964662134Z"
    description: A minimal HTTP server for static pages. Full version with "parking"
      HTML.
    digest: 0d28be80f4ae1c62505cb14e075434e88b3119ffd4b1c2d626df9d11df846b5d
    name: static-httpserver
    type: application
    urls:
    - https://opensource.byjg.com/helm/static-httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2024-01-12T20:37:13.96100966Z"
