apiVersion: v1
entries:
  easyhaproxy:
  - apiVersion: v2
    appVersion: test
    created: "2022-08-28T06:22:49.376364217Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: fcdf99bf482fd2830f1a6de441aa8d5d7dfc973633a035c063ad9a1bf9bb9f93
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.0.tgz
    version: 0.1.0
  static-httpserver:
  - apiVersion: v2
    appVersion: latest
    created: "2022-08-28T06:22:49.376814628Z"
    description: A minimal HTTP server for static pages. Full version with "parking"
      HTML.
    digest: ff711b4532dbf6897eed2bfbb07de99d6ab4f6eb30e15165e2d555dda9979fd5
    name: static-httpserver
    type: application
    urls:
    - https://opensource.byjg.com/helm/static-httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-28T06:22:49.375653699Z"
