apiVersion: v1
entries:
  easyhaproxy:
  - apiVersion: v2
    appVersion: 4.2.0
    created: "2022-09-02T06:35:43.792442578Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: d30114fe6c91cc648ea220e43cb4473d7703022f0fa27313355d0ba0af594b80
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: master
    created: "2022-09-02T06:35:43.79203377Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a111f02e52ff8b1c8be11f32c5a5ed43ad7f3cb6108d74de296a774e3dbc28a0
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: test
    created: "2022-09-02T06:35:43.79159516Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: a5dee1fe1c339cb4916fc076657db77957d12a2c87279acab1fded1501196e87
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: test
    created: "2022-09-02T06:35:43.791174251Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: e2019a2ec047d4289cabe25b7556b74411689e1612505a787ddd6c6d7730ce53
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: test
    created: "2022-09-02T06:35:43.790768342Z"
    description: EasyHAProxy - A service discovery backed on HAProxy
    digest: fcdf99bf482fd2830f1a6de441aa8d5d7dfc973633a035c063ad9a1bf9bb9f93
    name: easyhaproxy
    type: application
    urls:
    - https://opensource.byjg.com/helm/easyhaproxy-0.1.0.tgz
    version: 0.1.0
  static-httpserver:
  - apiVersion: v2
    appVersion: latest
    created: "2022-09-02T06:35:43.792811686Z"
    description: A minimal HTTP server for static pages. Full version with "parking"
      HTML.
    digest: 25900bad407e9a54495c28ba1791cfdd797e90e7324a27fa1f6168cdacf99682
    name: static-httpserver
    type: application
    urls:
    - https://opensource.byjg.com/helm/static-httpserver-0.1.0.tgz
    version: 0.1.0
generated: "2022-09-02T06:35:43.789945925Z"
